version: '3'
services:
  app:
    image: reprogle-api
    volumes:
      - type: bind
        source: ~/your/certs/folder
        target: /app/dist/certs
    ports:
      - "8080:8080"
    environment:
      WEBHOOK: "https://discord.com/api/webhooks/your_webhook_here"
      TURNSTILE_SECRET: '1x0000000000000000000000000000000AA'